- id: bark-code-review
  name: Bark Code Review
  description: 使用 Bark 进行代码审查
  entry: pre-commit.sh
  language: system
  types: [file]
  args: ["--url", "http://localhost:8080", "--token", ""]
  additional_dependencies: [jq] 