repos:
  - repo: https://github.com/jincong8973/bark
    rev: v0.0.1
    hooks:
      - id: bark-code-review
        name: Bark Code Review
        description: 使用 Bark 进行代码审查
        args: ["--url", "https://your-bark-service.com", "--token", "your-bark-token"] 